import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.servlet.jsp.tagext.*;
import java.io.IOException;
import java.beans.*;
import java.util.*;
public class _s_errorReport_D_jsp extends com.BajieSoft.jspCompiler._jsp_gzJspServlet {
public void _jspService(HttpServletRequest request, HttpServletResponse  response) throws IOException, ServletException 
{
    JspFactory _jsp_BjFactory = null;
    PageContext pageContext = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    Exception exception=null;
    try{
      _jsp_BjFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html");
      pageContext = _jsp_BjFactory.getPageContext(this,                            request,response, null, true, 8192, true);
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      HttpSession session = pageContext.getSession();
      out = pageContext.getOut();
      exception =pageContext.getException();
out.print("<html>\n<head><title>Error Happened</title></head>\n<body bgcolor=#aaaaee>\n<center><H1>Error Happened</H1></center><br><br>\n<hr><BR>\n");
//__BajieSrvJspDbgLine  File /errorReport.jsp line number 7

    
//__BajieSrvJspDbgLine  File /errorReport.jsp line number 9
    out.println("<pre>");
//__BajieSrvJspDbgLine  File /errorReport.jsp line number 10
    Throwable e=(Throwable)request.getAttribute("javax.servlet.error.Throwable");
    
//__BajieSrvJspDbgLine  File /errorReport.jsp line number 12
    if(e!=null){
//__BajieSrvJspDbgLine  File /errorReport.jsp line number 13
        e.printStackTrace(new java.io.PrintWriter(out));
//__BajieSrvJspDbgLine  File /errorReport.jsp line number 14
    }
    
//__BajieSrvJspDbgLine  File /errorReport.jsp line number 16
    if(e==null){
//__BajieSrvJspDbgLine  File /errorReport.jsp line number 17
      String errorMsg =(String) request.getAttribute("javax.servlet.error.message");
//__BajieSrvJspDbgLine  File /errorReport.jsp line number 18
      out.println(errorMsg);
//__BajieSrvJspDbgLine  File /errorReport.jsp line number 19
    }
//__BajieSrvJspDbgLine  File /errorReport.jsp line number 20
    out.println("</pre>");


out.print("\n<BR>\n<BR><hr>\n<font size=-2>page generated by errorReport servlet</font>\n</body></html>\n\n");
    }catch (Throwable _jsp_ex) {
      getServletConfig().getServletContext().log(getServletConfig().getServletName(),_jsp_ex);
      _jsp_ex=com.BajieSoft.jspCompiler.gzJspComponent.mapJspLN("defaultTmp/htdocs/_BajieJspTemp/_s_errorReport_D_jsp.java",_jsp_ex);
      pageContext.handlePageException(_jsp_ex);
    } finally {
      _jsp_BjFactory.releasePageContext(pageContext);
    }
}
public String[] _bjSrvGetJspDepNames(){return null;}
public long[] _bjSrvGetJspTimes(){return null;}
}