<html>
<body>
	<h1>The Famous JSP Hello Program</h1>
	<% String s = "JSP"; %>
The following line should contain the text "Hello JSP World!".
<br>If thats not the case start debugging ...
<p>
Hello <%= s %> World!
<br><p>Here is 10 Hello generated by jsp</p><br>
<% for (int i=0;i<10;i++){ %>
Hello <%= i %> <br>
<% } %>
</body>
</html>
 
